<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('GameCentral'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicongc.ico'))
                    ->prependStylesheet($this->basePath() . '/css/main.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/supersized.css')
                    ->prependStylesheet($this->basePath() . '/css/jquery.bxslider.css')
                    ->prependStylesheet($this->basePath() . '/css/animate.css')

                    //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                    //->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
</head>
<body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=287929584699013";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <div id="supersized"></div>
    <div id="wrap">
        <div id="topBackRepeat">    
            <div id="main">
                <header>
                    <div class="shadowblock">
                        <div class="logobar">
                            <a href="/"><img src="<?php echo $this->basePath('img/Logo.png') ?>" alt="GameCentral"></a>
                            <div class="social">
                                <a href="#" class="fb transition animated fadeInDown"></a>
                                <a href="#" class="tw transition animated fadeInDown"></a>
                                <a href="#" class="yt transition animated fadeInDown"></a>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                    <nav class="animated">
                        <ul>
                        <li><a href="/">Inicio</a></li>
                        <li><a href="/review">Reseñas</a></li>
                        <li><a href="#">Catalogo</a></li>
                        <li><a href="/sucursales">Sucursales</a></li>
                        <li><a href="/contacto">Contacto</a></li>                           
                        </ul>
                    </nav>
                    <div class="mist"></div>
                </header>
                <div id="mobileMenu">
                    <select name="#" id="#">
                        <option value="/">Inicio</option>
                        <option value="/review">Reseñas</option>
                        <option value="/">Catalogo</option>
                        <option value="/contacto">Contacto</option>

                    </select>
                </div>
                <div id="content">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
    </div>
    <div id="footer">
    <div class="container">
        <div class="column">
            <h3>Contáctanos</h3>
            <p>Tel. (998) 123-4567</p>
        </div>
        <div class="column middle">
            <h3>Redes Sociales</h3>
            <a href="#" class="fb"></a>
            <a href="#" class="tw"></a>
            <a href="#" class="yt"></a>

        </div>
        <div class="column right">
            <h3><a href="#">GameCentral</a></h3>
            <p>Copyright 2014</p>
            <p>Todos los derechos reservados</p>
        </div>
    </div>
    <div class="clear"></div>
    </div>


    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.bxslider.min.js')
        ->prependFile($this->basePath() . '/js/supersized.3.2.7.min.js')
        ->prependFile($this->basePath() . '/js/interactions.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')

        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</body>
</html>
